service: Igdb-Connector-Lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  test:
    handler: handler.test
    events:
      - httpApi:
          path: /test
          method: post

  games:
    handler: handler.getGames
    events:
      - httpApi:
          path: /games/{param}
          method: get

plugins:
  - serverless-offline